### ISSUE TITLE
dependency issue

### ISSUE THREAD

**Issue by dirteat** [DNSCrypt/dnscrypt-proxy#779]
Hi there,
with latest go implementation, trying to compile the source file leads to the download of ten of packages from various github repository, everything was working fine with dnscrypt-proxy-2.0.19, any ideas what could be going wrong? Any advice appreciated!

``
go: finding github.com/aead/chacha20 v0.0.0-20180709150244-8b13a72661da
go: finding github.com/jedisct1/go-dnsstamps v0.0.0-20190303171121-de46dd0ba576
go: finding github.com/kardianos/service v1.0.0
go: finding github.com/hashicorp/golang-lru v0.5.1
go: finding github.com/jedisct1/go-minisign v0.0.0-20180516093733-f4dbde220b4f
go: finding github.com/facebookgo/atomicfile v0.0.0-20151019160806-2de1f203e7d
``
Cheers,
Chris.

**Comment by eclipseo** [comment]
2.0.19 was vendoring deps, while since 2.0.20 it is using Go modules.
What is the issue exactly? Your code snippet doesn't show any error, it is fetching dependencies as expected.

**Comment by dirteat** [comment]
Arg! I am packaging it for a distro, which means security issues forbid us to compile source codes fetching other sources from the internet. I guess I'll have to either package missing go modules or vendor deps myself then.

Thanks for the explanations!

Would be nice to have a switch somewhere disabling auto-fetching and triggering an error for missing deps though!

Cheers,
Chris.

**Comment by jedisct1** [comment]
The `vendor` directory is still here.

**Comment by dirteat** [comment]
I guess it is not up to date with golangv  1.12, get some compilation errors with 1.12, while it compiles fine with 1.11.

```
 # vendor/vendor/golang.org/x/net/idna
src/vendor/vendor/golang.org/x/net/idna/idna.go:338:51: invalid operation: bidirule.DirectionString(u) != "vendor/vendor/vendor/golang.org/x/text/unicode/bidi".LeftToRight (mismatched types "vendor/vendor/vendor/vendor/golang.org/x/text/unicode/bidi".Direction and "vendor/vendor/vendor/golang.org/x/text/unicode/bidi".Direction)
src/vendor/vendor/golang.org/x/net/idna/idna.go:397:44: invalid operation: bidirule.DirectionString(mapped) == "vendor/vendor/vendor/golang.org/x/text/unicode/bidi".RightToLeft (mismatched types "vendor/vendor/vendor/vendor/golang.org/x/text/unicode/bidi".Direction and "vendor/vendor/vendor/golang.org/x/text/unicode/bidi".Direction)
# vendor/golang.org/x/net/idna
src/vendor/golang.org/x/net/idna/idna.go:338:51: invalid operation: bidirule.DirectionString(u) != "vendor/vendor/golang.org/x/text/unicode/bidi".LeftToRight (mismatched types "vendor/vendor/vendor/golang.org/x/text/unicode/bidi".Direction and "vendor/vendor/golang.org/x/text/unicode/bidi".Direction)
src/vendor/golang.org/x/net/idna/idna.go:397:44: invalid operation: bidirule.DirectionString(mapped) == "vendor/vendor/golang.org/x/text/unicode/bidi".RightToLeft (mismatched types "vendor/vendor/vendor/golang.org/x/text/unicode/bidi".Direction and "vendor/vendor/golang.org/x/text/unicode/bidi".Direction)
```

**Comment by jedisct1** [comment]
These were built using Go 1.12.1

**Comment by dirteat** [comment]
Finally succeeded to compile, I had to remove the go.mod and go.sum files, plus, some minor changes between 1.11 and 1.12.1 were interfering. I am closing, would be nice if you could still keep that vendor directory there in future versions.
Thanks,
Cheers,Chris.

**Comment by eclipseo** [comment]
> Arg! I am packaging it for a distro, which means security issues forbid us to compile source codes fetching other sources from the internet. I guess I'll have to either package missing go modules or vendor deps myself then.
> 
> Thanks for the explanations!
> 
> Would be nice to have a switch somewhere disabling auto-fetching and triggering an error for missing deps though!
> 
> Cheers,
> Chris.

Which distro?
As a Go packager, you should be aware of the move to Go modules, which causes difficulties for us packagers. It will be the default for Go 1.13 in August.

> Finally succeeded to compile, I had to remove the go.mod and go.sum files, plus, some minor changes between 1.11 and 1.12.1 were interfering. I am closing, would be nice if you could still keep that vendor directory there in future versions.
> Thanks,
> Cheers,Chris.

You shouldn't do that but instead pass the environment variable GO111MODULE=off

**Comment by dirteat** [comment]
Thanks for the info, this is for Mageia and we have only a few modules already packaged, which indeed makes it a hell if modules are the only option.

In addition, I am not familiar with go, was just packaging dnscrypt-proxy v1 and was forced to step up to play with "go" for v2 :-/
